# Generated by Django 2.0.3 on 2018-03-19 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20180319_2139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={},
        ),
    ]
