# Generated by Django 2.0.3 on 2018-04-01 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_auto_20180325_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'Подписчик', 'verbose_name_plural': 'Подписчики'},
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='name',
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(help_text='llkk', max_length=254),
        ),
    ]
